/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define GPIOA_BASE  0x40010800
#define GPIOA_CRH   (*(volatile uint32_t *)(GPIOA_BASE + 0x04))
#define GPIOA_ODR   (*(volatile uint32_t *)(GPIOA_BASE + 0x0C))
//Enabling clock
#define RCC_BASE  0x40021000
#define RCC_APB2ENR   (*(volatile uint32_t *)(RCC_BASE + 0x18))

int main(void)
{
    // GPIO init
    GPIOA_CRH &= 0xFFFFFFF0;
    GPIOA_CRH |= 0x00000002;

    while (1)
    {
        GPIOA_ODR |= (1 << 13); // Set Pin 13
        for (int i = 0; i < 10000; i++);
        GPIOA_ODR &= ~(1 << 13); // reset Pin 13
        for (int i = 0; i < 10000; i++);
    }
}
