/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define GPIOA_BASE  0x40010800
#define GPIOA_CRH   (*(volatile uint32_t *)(GPIOA_BASE + 0x04))
#define GPIOA_ODR   (*(volatile uint32_t *)(GPIOA_BASE + 0x0C))
//Enabling clock
#define RCC_BASE  0x40021000
#define RCC_APB2ENR   (*(volatile uint32_t *)(RCC_BASE + 0x18))
#define RCC_CR       (*(volatile uint32_t *)(RCC_BASE + 0x00))
#define RCC_CFGR     (*(volatile uint32_t *)(RCC_BASE + 0x04))

int main(void)
{
	// Enable HSI (default on, but just in case)
	RCC_CR |= (1 << 0); // HSI ON

	// Wait until HSI is ready
	while ((RCC_CR & (1 << 1)) == 0);

	// Set AHB = SYSCLK (no division)
	// Set APB1 = HCLK / 2 → 4 MHz
	// Set APB2 = HCLK / 4 → 2 MHz
	RCC_CFGR &= ~((0b111 << 4) | (0b111 << 8) | (0b111 << 11)); // Clear HPRE, PPRE1, PPRE2
	RCC_CFGR |= (0b100 << 8);  // PPRE1: divide by 2
	RCC_CFGR |= (0b101 << 11); // PPRE2: divide by 4

	// Select HSI as system clock
	RCC_CFGR &= ~(0b11 << 0); // Clear SW bits
	RCC_CFGR |= (0b00 << 0);  // Set HSI as SYSCLK

	// Wait until HSI is used as system clock
	while (((RCC_CFGR >> 2) & 0b11) != 0b00);
    // GPIO init
    GPIOA_CRH &= 0xFFFFFFF0;
    GPIOA_CRH |= 0x00000002;

    while (1)
    {
        GPIOA_ODR |= (1 << 13); // Set Pin 13
        for (int i = 0; i < 10000; i++);
        GPIOA_ODR &= ~(1 << 13); // reset Pin 13
        for (int i = 0; i < 10000; i++);
    }
}
